#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=/dev/null
source "$SCRIPT_DIR/gvt-direct-env.sh"

CLIENT_HOST=${1:-${CLIENT_HOST:-}}
PORT=${PORT:-5004}
FPS=${FPS:-60}
BITRATE_KBPS=${BITRATE_KBPS:-12000}
FEC_PERCENTAGE=${FEC_PERCENTAGE:-20}
FEC_PERCENTAGE_IMPORTANT=${FEC_PERCENTAGE_IMPORTANT:-60}
GVT_CONVERT=${GVT_CONVERT:-vaapi}
GVT_ADAPTIVE=${GVT_ADAPTIVE:-1}
GVT_SOURCE_MODE=${GVT_SOURCE_MODE:-copy}
GVT_IDLE_FPS=${GVT_IDLE_FPS:-8}
GVT_IDLE_AFTER_MS=${GVT_IDLE_AFTER_MS:-350}
GVT_KEEPALIVE_MS=${GVT_KEEPALIVE_MS:-1000}

if [ -z "$CLIENT_HOST" ] && [ -n "${SSH_CONNECTION:-}" ]; then
  CLIENT_HOST=$(printf '%s\n' "$SSH_CONNECTION" | awk '{print $1}')
fi

if [ -z "$CLIENT_HOST" ]; then
  echo "usage: $0 <client-ip>" >&2
  echo "or set CLIENT_HOST=<client-ip>" >&2
  exit 2
fi

exec env FEC_PERCENTAGE="$FEC_PERCENTAGE" FEC_PERCENTAGE_IMPORTANT="$FEC_PERCENTAGE_IMPORTANT" \
  GVT_CONVERT="$GVT_CONVERT" GVT_ADAPTIVE="$GVT_ADAPTIVE" GVT_IDLE_FPS="$GVT_IDLE_FPS" \
  GVT_SOURCE_MODE="$GVT_SOURCE_MODE" \
  GVT_IDLE_AFTER_MS="$GVT_IDLE_AFTER_MS" GVT_KEEPALIVE_MS="$GVT_KEEPALIVE_MS" \
  "$SCRIPT_DIR/gvt-shadowfb-rtp" "$CLIENT_HOST" "$PORT" "$FPS" "$BITRATE_KBPS"
